# Generated by Django 4.2.7 on 2023-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
                ('CPassword', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(max_length=254)),
                ('MobileNumber', models.IntegerField()),
            ],
        ),
    ]
